#!/usr/bin/env php
<?php

/**
 * This file is part of content.videosz.com
 *
 * (c) Aaron Scherer <aequasi@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE
 */

use Doctrine\Common\Annotations\AnnotationRegistry;
use Composer\Autoload\ClassLoader;

/**
 * @var ClassLoader $loader
 */
$loader = require __DIR__.'/../vendor/autoload.php';
AnnotationRegistry::registerLoader([$loader, 'loadClass']);

require __DIR__.'/../app/Kernel.php';
\Symforium\Core\Console::create(new \Symforium\Web\Kernel());
